Project {
  database_type: 'PostgreSQL'
}

Table "spatial_ref_sys" {
  "srid" integer [pk, not null]
  "auth_name" varchar(256)
  "auth_srid" integer
  "srtext" varchar(2048)
  "proj4text" varchar(2048)
}

Table "post_tags" {
  "id" integer [pk, increment, not null]
  "post_id" integer [not null]
  "tag_id" integer [not null]

  indexes {
    ("post_id", "tag_id") [unique, name: "post_tags_post_id_tag_id_key"]
    ("post_id") [name: "post_tags_post_id_idx"]
    ("tag_id") [name: "post_tags_tag_id_idx"]
  }
}

Table "abc_posts" {
  "abc_id" integer [pk, increment, not null]
  "abc_user_id" integer [not null]
  "abc_category_id" integer [not null]
  "abc_content" varchar(255) [not null]

  indexes {
    ("abc_category_id") [name: "abc_posts_category_id_idx"]
    ("abc_user_id") [name: "abc_posts_user_id_idx"]
  }
}

Table "tags" {
  "id" integer [pk, increment, not null]
  "name" varchar(255) [not null]
  "is_important" boolean [not null]
}

Table "users" {
  "id" integer [pk, increment, not null]
  "username" varchar(255) [not null]
  "password" varchar(255) [not null]
  "api_key" varchar(255)
  "location" public.geometry
}

Table "countries" {
  "id" integer [pk, increment, not null]
  "name" varchar(255) [not null]
  "shape" public.geometry [not null]
}

Table "events" {
  "id" integer [pk, increment, not null]
  "name" varchar(255) [not null]
  "datetime" timestamp
  "visitors" bigint
}

Table "products" {
  "id" integer [pk, increment, not null]
  "name" varchar(255) [not null]
  "price" numeric(10,2) [not null]
  "properties" json [not null]
  "created_at" timestamp [not null]
  "deleted_at" timestamp
}

Table "barcodes" {
  "id" integer [pk, increment, not null]
  "product_id" integer [not null]
  "hex" varchar(255) [not null]
  "bin" bytea [not null]
  "ip_address" varchar(15)

  indexes {
    ("product_id") [name: "barcodes_product_id_idx"]
  }
}

Table "kunsthåndværk" {
  "id" varchar(36) [pk, not null]
  "Umlauts ä_ö_ü-COUNT" integer [unique, not null]
  "user_id" integer [not null]
  "invisible" varchar(36)
  "invisible_id" varchar(36)

  indexes {
    ("Umlauts ä_ö_ü-COUNT") [name: "kunsthåndværk_Umlauts ä_ö_ü-COUNT_idx"]
    ("invisible_id") [name: "kunsthåndværk_invisible_id_idx"]
    ("user_id") [name: "kunsthåndværk_user_id_idx"]
  }
}

Table "invisibles" {
  "id" varchar(36) [pk, not null]
}

Table "nopk" {
  "id" varchar(36) [not null]
}

Ref: "abc_posts"."abc_user_id" > "users"."id"
Ref: "barcodes"."product_id" > "products"."id"
Ref: "kunsthåndværk"."invisible_id" > "invisibles"."id"
Ref: "kunsthåndværk"."user_id" > "users"."id"
Ref: "post_tags"."post_id" > "abc_posts"."abc_id"
Ref: "post_tags"."tag_id" > "tags"."id"
