#!/usr/bin/env bash
#
# Publish the current VERSION as a GitHub release and upload the binaries.
#
# What it does:
#   1. reads ./VERSION            → tag name "v<VERSION>"
#   2. cross-compiles + archives  → ./scripts/build-binaries.sh --archives
#   3. verifies dist/SHA256SUMS
#   4. creates and pushes the tag (if it does not exist yet)
#   5. creates the release, or updates it if the tag already has one,
#      uploading every archive plus SHA256SUMS
#
# Assets uploaded (matching the layout of earlier releases):
#   dbml-tools-<version>-linux-x64.tar.gz     dbml-tools-<version>-win32-x64.zip
#   dbml-tools-<version>-linux-arm64.tar.gz   dbml-tools-<version>-win32-arm64.zip
#   dbml-tools-<version>-darwin-x64.tar.gz    SHA256SUMS
#   dbml-tools-<version>-darwin-arm64.tar.gz
#
# Usage:
#   ./scripts/gh-release.sh                       # build + release v<VERSION>
#   ./scripts/gh-release.sh --title "Some title"  # release title (default: "dbml-tools <version>")
#   ./scripts/gh-release.sh --notes "..."         # release notes (default: generated by gh)
#   ./scripts/gh-release.sh --notes-file NOTES.md # release notes from a file
#   ./scripts/gh-release.sh --draft               # create as a draft
#   ./scripts/gh-release.sh --prerelease          # mark as a prerelease
#   ./scripts/gh-release.sh --skip-build          # reuse whatever is in ./dist
#   ./scripts/gh-release.sh --allow-dirty         # skip the clean-tree check
#   ./scripts/gh-release.sh --dry-run             # show what would happen, change nothing
#
# Requires: gh (authenticated with `gh auth login`), git, zip, tar, a Go toolchain.

set -euo pipefail

cd "$(dirname "$0")/.."

DIST=dist
BIN=dbml-tools

TITLE=""
NOTES=""
NOTES_FILE=""
DRAFT=0
PRERELEASE=0
SKIP_BUILD=0
ALLOW_DIRTY=0
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --title)       TITLE=${2:?--title needs a value}; shift 2 ;;
    --notes)       NOTES=${2:?--notes needs a value}; shift 2 ;;
    --notes-file)  NOTES_FILE=${2:?--notes-file needs a value}; shift 2 ;;
    --draft)       DRAFT=1; shift ;;
    --prerelease)  PRERELEASE=1; shift ;;
    --skip-build)  SKIP_BUILD=1; shift ;;
    --allow-dirty) ALLOW_DIRTY=1; shift ;;
    --dry-run)     DRY_RUN=1; shift ;;
    -h|--help)     sed '1d' "$0" | grep '^#' | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)             echo "unknown option: $1 (try --help)" >&2; exit 1 ;;
  esac
done

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf 'would run:'; printf ' %q' "$@"; printf '\n'
  else
    "$@"
  fi
}

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

command -v gh >/dev/null 2>&1 || { echo "gh not found — install the GitHub CLI" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not authenticated — run 'gh auth login'" >&2; exit 1; }

[ -f VERSION ] || { echo "VERSION file not found at $(pwd)/VERSION" >&2; exit 1; }
VERSION=$(tr -d '[:space:]' < VERSION)
[ -n "$VERSION" ] || { echo "VERSION file is empty" >&2; exit 1; }
TAG="v$VERSION"

if [ "$ALLOW_DIRTY" != "1" ]; then
  if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "working tree has uncommitted changes — commit them first" >&2
    echo "(the commit hash is baked into the binaries; use --allow-dirty to override)" >&2
    git status --short >&2
    exit 1
  fi
fi

COMMIT=$(git rev-parse HEAD)

# A tag that already exists must point at the commit we are releasing.
if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
  TAGGED=$(git rev-list -n 1 "$TAG")
  if [ "$TAGGED" != "$COMMIT" ]; then
    echo "tag $TAG already exists but points at $TAGGED, not HEAD ($COMMIT)" >&2
    echo "bump VERSION, or delete the tag with: git tag -d $TAG && git push origin :$TAG" >&2
    exit 1
  fi
  echo "tag $TAG already exists at HEAD"
  TAG_EXISTS=1
else
  TAG_EXISTS=0
fi

echo "releasing $TAG from $(git rev-parse --short HEAD)"

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

if [ "$SKIP_BUILD" = "1" ]; then
  echo "skipping build, reusing $DIST/"
else
  run ./scripts/build-binaries.sh --archives
fi

ASSETS=(
  "$DIST/$BIN-$VERSION-linux-x64.tar.gz"
  "$DIST/$BIN-$VERSION-linux-arm64.tar.gz"
  "$DIST/$BIN-$VERSION-darwin-x64.tar.gz"
  "$DIST/$BIN-$VERSION-darwin-arm64.tar.gz"
  "$DIST/$BIN-$VERSION-win32-x64.zip"
  "$DIST/$BIN-$VERSION-win32-arm64.zip"
  "$DIST/SHA256SUMS"
)

if [ "$DRY_RUN" != "1" ]; then
  missing=0
  for a in "${ASSETS[@]}"; do
    if [ ! -f "$a" ]; then
      echo "missing asset: $a" >&2
      missing=1
    fi
  done
  [ "$missing" = "0" ] || { echo "run without --skip-build to produce them" >&2; exit 1; }

  # The checksums must match what we are about to upload.
  (cd "$DIST" && sha256sum -c --quiet SHA256SUMS)
  echo "checksums verified"
fi

# ---------------------------------------------------------------------------
# Tag
# ---------------------------------------------------------------------------

if [ "$TAG_EXISTS" = "0" ]; then
  run git tag -a "$TAG" -m "$TAG"
fi
run git push origin "$TAG"

# ---------------------------------------------------------------------------
# Release
# ---------------------------------------------------------------------------

[ -n "$TITLE" ] || TITLE="$BIN $VERSION"

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "release $TAG exists — uploading assets with --clobber"
  run gh release upload "$TAG" "${ASSETS[@]}" --clobber
else
  CREATE=(gh release create "$TAG" "${ASSETS[@]}" --title "$TITLE")
  if [ -n "$NOTES_FILE" ]; then
    CREATE+=(--notes-file "$NOTES_FILE")
  elif [ -n "$NOTES" ]; then
    CREATE+=(--notes "$NOTES")
  else
    CREATE+=(--generate-notes)
  fi
  if [ "$DRAFT" = "1" ]; then CREATE+=(--draft); fi
  if [ "$PRERELEASE" = "1" ]; then CREATE+=(--prerelease); fi
  run "${CREATE[@]}"
fi

if [ "$DRY_RUN" != "1" ]; then
  echo
  gh release view "$TAG" --json url --jq .url
fi
